name: Dockerize App

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main           # or any branch you prefer

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to DockerHub (use GHCR if you prefer)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build images using docker-compose
      - name: Build and Pull Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml pull
      #List docker images
      - name: List docker images
        run: docker images
      #Re-Tag Myapp and mysql
      - name: Retag MyApp and MySQL
        run:
          docker tag myblog-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/myblog-app:latest
          docker tag mysql:8.0.43 ${{ secrets.DOCKERHUB_USERNAME }}/mysql:8.0.43
      # Push your app image
      - name: Push MyApp image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myblog-app:latest

      # Push MySQL image (only if you modified Dockerfile, otherwise use official mysql:8.0)
      - name: Push MySQL image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql:8.0.43
