# This workflow will build a Spring project with mysql dependency with Maven,
# and cache/restore any dependencies to improve the workflow execution time

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: MySQL@2022
          MYSQL_DATABASE: spring_db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
          - name: Wait for MySQL
              run: |
                sudo apt-get install -y mysql-client
                until mysql -h127.0.0.1 -P3306 -uroot -pMySQL@2022 -e "SELECT 1"; do
                  echo "Waiting for MySQL..."
                  sleep 5
                done
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
